# Tugas 2


## 1. Carilah data yang bertipe numerik (data klasifikasi)

In [243]:
import pandas as pd
import numpy as np

In [244]:
# source data
dataset_url = "https://raw.githubusercontent.com/Ihsan210702/dataset/main/IRIS.csv"

In [245]:
# membuat dataframe
df = pd.read_csv(dataset_url)

In [246]:
# Menampilkan dataset iris
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [247]:
# show first 15 rows
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [248]:
# CONSTAN SERIES

sepal_length = df["sepal_length"]
sepal_width = df["sepal_width"]
petal_length = df["petal_length"]
petal_width = df["petal_width"]

## 2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*

### Tentang *diskritisasi*

1. Proses mengubah data bertipe data *numeric* menjadi data bertipe *categorical*
2. Diskritisasi memiliki 2 pendekatan yaitu *equal-width intervals* dan *equal-frequency intervals*
3. *equal-width intervals* adalah diskritisasi dengan lebar data yang sama
4. *equal-frequency intervals* adalah diskritisasi dengan jumlah data yang sama

#### Equal-width Intervals
Equal-width intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

Untuk menghitung equal width, dibutuhkan library pandas dengan menggunakan method "Cut". Buatlah 3 label untuk mengkategorikan batas tiap ukuran petal dan sepal disini saya menggunakan label kecil, sedang, besar.

#### Cut

* Cut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal width intervals*


```
# Syntax
pd.cut(series, interval, right=True, label)
```

##### Sepal Width

* Equal Width Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [249]:
# equal-width intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(sepal_width, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(sepal_width, amount_of_binning, True).value_counts()

In [250]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_width, sepal_width_ew_binning), axis=1)

    sepal_width sepal_width
0           3.5      Sedang
1           3.0      Sedang
2           3.2      Sedang
3           3.1      Sedang
4           3.6      Sedang
..          ...         ...
145         3.0      Sedang
146         2.5       Kecil
147         3.0      Sedang
148         3.4      Sedang
149         3.0      Sedang

[150 rows x 2 columns]

In [251]:
# equal-width intervals binning with label
labelled_sepal_width_ew_binning

Sedang    88
Kecil     47
Besar     15
Name: sepal_width, dtype: int64

In [252]:
# equal-width intervals without label
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

##### Petal Width

* Equal Width Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [253]:
# equal-width intervals
labels = labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

petal_width_ew_binning = pd.cut(petal_width, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(petal_width, amount_of_binning, True).value_counts()

In [254]:
# dataframe of petal-width and petal category
pd.concat((petal_width, petal_width_ew_binning), axis=1)

    petal_width petal_width
0           0.2       Kecil
1           0.2       Kecil
2           0.2       Kecil
3           0.2       Kecil
4           0.2       Kecil
..          ...         ...
145         2.3       Besar
146         1.9       Besar
147         2.0       Besar
148         2.3       Besar
149         1.8       Besar

[150 rows x 2 columns]

In [255]:
# equal-width intervals with label
labelled_petal_width_ew_binning

Sedang    54
Kecil     50
Besar     46
Name: petal_width, dtype: int64

In [256]:
# equal-width intervals without label
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal_width, dtype: int64

##### Sepal Length

* Equal Width Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [257]:
# equal-width intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

sepal_length_ew_binning = pd.cut(sepal_length, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(sepal_length, amount_of_binning, True).value_counts()

In [258]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_length, sepal_length_ew_binning), axis=1)

    sepal_length sepal_length
0            5.1        Kecil
1            4.9        Kecil
2            4.7        Kecil
3            4.6        Kecil
4            5.0        Kecil
..           ...          ...
145          6.7       Sedang
146          6.3       Sedang
147          6.5       Sedang
148          6.2       Sedang
149          5.9       Sedang

[150 rows x 2 columns]

In [259]:
# equal-width intervals with label
labelled_sepal_length_ew_binning

Sedang    71
Kecil     59
Besar     20
Name: sepal_length, dtype: int64

In [260]:
# equal-width intervals without label
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal_length, dtype: int64

##### Petal Length

* Equal Width Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [261]:
# equal-width intervals
labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

petal_length_ew_binning = pd.cut(petal_length, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(petal_length, amount_of_binning, True).value_counts()

In [262]:
# dataframe of petal-width and petal category
pd.concat((petal_length,petal_length_ew_binning), axis=1)

    petal_length petal_length
0            1.4        Kecil
1            1.4        Kecil
2            1.3        Kecil
3            1.5        Kecil
4            1.4        Kecil
..           ...          ...
145          5.2        Besar
146          5.0        Besar
147          5.2        Besar
148          5.4        Besar
149          5.1        Besar

[150 rows x 2 columns]

In [263]:
# equal-width intervals binning with label
labelled_petal_length_ew_binning

Sedang    54
Kecil     50
Besar     46
Name: petal_length, dtype: int64

In [264]:
# equal-width intervals out label
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal_length, dtype: int64

### Data Categorical Equal Width

In [265]:
pd.concat((sepal_width_ew_binning,petal_width_ew_binning,sepal_length_ew_binning,petal_length_ew_binning), axis=1)

    sepal_width petal_width sepal_length petal_length
0        Sedang       Kecil        Kecil        Kecil
1        Sedang       Kecil        Kecil        Kecil
2        Sedang       Kecil        Kecil        Kecil
3        Sedang       Kecil        Kecil        Kecil
4        Sedang       Kecil        Kecil        Kecil
..          ...         ...          ...          ...
145      Sedang       Besar       Sedang        Besar
146       Kecil       Besar       Sedang        Besar
147      Sedang       Besar       Sedang        Besar
148      Sedang       Besar       Sedang        Besar
149      Sedang       Besar       Sedang        Besar

[150 rows x 4 columns]

#### Equal-frequency Intervals
Equal-frequency intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

Untuk menghitung equal width, dibutuhkan library pandas dengan menggunakan method "Qcut". Buatlah 3 label untuk mengkategorikan batas tiap ukuran petal dan sepal disini saya menggunakan label kecil, sedang, besar.

#### Qcut
* Qcut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal frequency intervals*

```
# Syntax
pd.qcut(series, interval, label)
```

##### Sepal Width

* Equal Frequency Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [266]:
# equal-frequency intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(sepal_width, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(sepal_width, amount_of_binning).value_counts()

In [267]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_width, sepal_width_ef_binning), axis = 1)

    sepal_width sepal_width
0           3.5       Besar
1           3.0      Sedang
2           3.2      Sedang
3           3.1      Sedang
4           3.6       Besar
..          ...         ...
145         3.0      Sedang
146         2.5       Kecil
147         3.0      Sedang
148         3.4       Besar
149         3.0      Sedang

[150 rows x 2 columns]

In [268]:
# equal-frequency intervals binning with label
labelled_sepal_width_ef_binning

Kecil     57
Sedang    51
Besar     42
Name: sepal_width, dtype: int64

In [269]:
# equal-frequency intervals out label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepal_width, dtype: int64

##### Petal Width

* Equal Frequency Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [270]:
# equal-frequency intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(petal_width, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(petal_width, amount_of_binning).value_counts()

In [271]:
# dataframe of petal-width and petal category
pd.concat((petal_width, petal_width_ef_binning), axis = 1)

    petal_width petal_width
0           0.2       Kecil
1           0.2       Kecil
2           0.2       Kecil
3           0.2       Kecil
4           0.2       Kecil
..          ...         ...
145         2.3       Besar
146         1.9       Besar
147         2.0       Besar
148         2.3       Besar
149         1.8       Besar

[150 rows x 2 columns]

In [272]:
# equal-frequency intervals binning with label
labelled_petal_width_ef_binning

Sedang    52
Kecil     50
Besar     48
Name: petal_width, dtype: int64

In [273]:
# equal-frequency intervals without label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal_width, dtype: int64

##### Sepal Length

* Equal Frequency Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [274]:
# equal-frequency intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(sepal_length, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(sepal_length, amount_of_binning).value_counts()

In [275]:
# dataframe of sepal-length and sepal category
pd.concat((sepal_length, sepal_length_ef_binning), axis=1)

    sepal_length sepal_length
0            5.1        Kecil
1            4.9        Kecil
2            4.7        Kecil
3            4.6        Kecil
4            5.0        Kecil
..           ...          ...
145          6.7        Besar
146          6.3       Sedang
147          6.5        Besar
148          6.2       Sedang
149          5.9       Sedang

[150 rows x 2 columns]

In [276]:
# equal-frequency intervals binning with label
labelled_sepal_length_ef_binning

Sedang    56
Kecil     52
Besar     42
Name: sepal_length, dtype: int64

In [277]:
# equal-frequency intervals out label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal_length, dtype: int64

##### Petal Length

* Equal Frequency Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori Kecil
* Kategori Sedang
* Kategori Besar

In [278]:
# equal-frequency intervals

labels = ["Kecil", "Sedang", "Besar"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(petal_length, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(petal_length, amount_of_binning).value_counts()

In [279]:
# dataframe of petal-length and petal category
pd.concat((petal_length, petal_length_ef_binning), axis=1)

    petal_length petal_length
0            1.4        Kecil
1            1.4        Kecil
2            1.3        Kecil
3            1.5        Kecil
4            1.4        Kecil
..           ...          ...
145          5.2        Besar
146          5.0        Besar
147          5.2        Besar
148          5.4        Besar
149          5.1        Besar

[150 rows x 2 columns]

In [280]:
# equal-frequency intervals binning with label
labelled_petal_length_ef_binning

Sedang    54
Kecil     50
Besar     46
Name: petal_length, dtype: int64

In [281]:
# equal-frequency intervals out label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal_length, dtype: int64

Data Categorical Equal Frequency

In [282]:
pd.concat((sepal_width_ef_binning,petal_width_ef_binning,sepal_length_ef_binning,petal_length_ef_binning), axis=1)

    sepal_width petal_width sepal_length petal_length
0         Besar       Kecil        Kecil        Kecil
1        Sedang       Kecil        Kecil        Kecil
2        Sedang       Kecil        Kecil        Kecil
3        Sedang       Kecil        Kecil        Kecil
4         Besar       Kecil        Kecil        Kecil
..          ...         ...          ...          ...
145      Sedang       Besar        Besar        Besar
146       Kecil       Besar       Sedang        Besar
147      Sedang       Besar        Besar        Besar
148       Besar       Besar       Sedang        Besar
149      Sedang       Besar       Sedang        Besar

[150 rows x 4 columns]

## 3. Lakukan proses diskritisasi dengan basis *entropy*

*Diskritisasi berbasis entropi (entropy based discretization)* adalah salah satu jenis algoritma diskritisasi terawasi yang menggunakan mekanisme top- down. Tujuan dari algoritma ini adalah mendapatkan partisi yang mengandung baris data dari kelas yang sama sebanyak mungkin.

*   Rumus Entropy:



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

>*   Rumus Gain:



$$Gain(E_{new}) = E_{initial} - E_{new}$$
>*   Rumus Info:



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$


Membuat sample data untuk di analisis

In [283]:
sample = df[["petal_width","petal_length","sepal_width","sepal_length"]]
sample.describe()

       petal_width  petal_length  sepal_width  sepal_length
count   150.000000    150.000000   150.000000    150.000000
mean      1.198667      3.758667     3.054000      5.843333
std       0.763161      1.764420     0.433594      0.828066
min       0.100000      1.000000     2.000000      4.300000
25%       0.300000      1.600000     2.800000      5.100000
50%       1.300000      4.350000     3.000000      5.800000
75%       1.800000      5.100000     3.300000      6.400000
max       2.500000      6.900000     4.400000      7.900000

Membuat category random untuk semua data

In [284]:
np.random.seed(0)
sample["Kategori"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

     petal_width  petal_length  sepal_width  sepal_length Kategori
0            0.2           1.4          3.5           5.1        A
1            0.2           1.4          3.0           4.9        B
2            0.2           1.3          3.2           4.7        B
3            0.2           1.5          3.1           4.6        A
4            0.2           1.4          3.6           5.0        B
..           ...           ...          ...           ...      ...
145          2.3           5.2          3.0           6.7        A
146          1.9           5.0          2.5           6.3        B
147          2.0           5.2          3.0           6.5        B
148          2.3           5.4          3.4           6.2        B
149          1.8           5.1          3.0           5.9        B

[150 rows x 5 columns]

Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [285]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("Kategori").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a,b,a+b)

Fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [286]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("Kategori").count()
  greater_group = greater.loc[:, :].groupby("Kategori").count()

  #get value based on category
  less_category_A = less_group.loc["A",col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc["A",col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Buat fungsi entropy untuk mencari nilai entropy

In [287]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

Membuat fungsi info dan gain

In [288]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

In [289]:
def gain(Einitial, Enew):
  return Einitial - Enew

#### Petal Width

Membuat Dinitial

In [290]:
a = GetOverollCategory("petal_width")
entropy_a = entropy(a)
print(a)
print(entropy_a)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

* Split 1 : 0.2

In [291]:
split1 = splitter(0.2, "petal_width")
info_split1 = info(split1)
gain(entropy_a, info_split1)

0.004337853351645382

* Split 2 : 1.2

In [296]:
split2 = splitter(1.2, "petal_width")
info_split2 = info(split2)
gain(entropy_a, info_split2)

0.00014982382104400394

* Split 3 : 2.4

In [300]:
split3 = splitter(2.4, "petal_width")
info_split3 = info(split3)
gain(entropy_a, info_split3)

0.0008771143281794958

Percobaan split pada atribut petal_width didapatkan bawah split terbaik yaitu split 2 yang memberikan keuntungan informasi sebesar 0.00014982382104400394 karena yang paling rendah

### Petal Length

Membuat Dinitial

In [302]:
b = GetOverollCategory("petal_length")
entropy_b = entropy(b)
print(b)
print(entropy_b)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

* Split 1 : 1.2

In [304]:
split1 = splitter(1.2, "petal_length")
info_split1 = info(split1)
gain(entropy_b, info_split1)

0.003488151753460178

* Split 2 : 3.3

In [305]:
split2 = splitter(3.3, "petal_length")
info_split2 = info(split2)
gain(entropy_b, info_split2)

0.002332399052385359

* Split 3 : 6.5

In [307]:
split3 = splitter(6.5, "petal_length")
info_split3 = info(split3)
gain(entropy_b, info_split3)

0.0001729324189373438

Percobaan split pada atribut petal_length didapatkan bawah split terbaik yaitu split 3 yang memberikan keuntungan informasi sebesar 0.0001729324189373438 karena yang paling rendah

### Sepal Width

Membuat Dinitial

In [313]:
c = GetOverollCategory("sepal_width")
entropy_c = entropy(c)
print(c)
print(entropy_c)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

* Split 1 : 2.2

In [315]:
split1 = splitter(2.2, "sepal_width")
info_split1 = info(split1)
gain(entropy_c, info_split1)

0.0001729324189373438

* Split 2 : 3.3

In [320]:
split2 = splitter(3.2, "sepal_width")
info_split2 = info(split2)
gain(entropy_c, info_split2)

1.0267936461083593e-06

* Split 3 : 4.0

In [319]:
split3 = splitter(4.0, "sepal_width")
info_split3 = info(split3)
gain(entropy_c, info_split3)

0.00271470605919788

Percobaan split pada atribut sepal_width didapatkan bawah split terbaik yaitu split 1 yang memberikan keuntungan informasi sebesar 0.0001729324189373438 karena yang paling rendah

### Sepal Length

Membuat Dinitial

In [321]:
d = GetOverollCategory("sepal_length")
entropy_d = entropy(d)
print(d)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

* Split 1 : 4.6

In [324]:
split1 = splitter(4.6, "sepal_length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.010619322724784941

* Split 2 : 5.8

In [325]:
split2 = splitter(5.8, "sepal_length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.0038893799103313365

* Split 3 : 7.6

In [328]:
split3 = splitter(7.6, "sepal_length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0069930419733333915

Percobaan split pada atribut sepal_length didapatkan bawah split terbaik yaitu split 3 yang memberikan keuntungan informasi sebesar 0.0069930419733333915 karena yang paling rendah